# Generated by Django 4.2.2 on 2023-06-16 06:55

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_mrvuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mrvuser',
            managers=[
                ('objects', users.models.MrvUserManager()),
            ],
        ),
    ]
