# Generated by Django 4.2.2 on 2023-06-11 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shells.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Difficulty Level',
                'verbose_name_plural': 'Difficulty Levels',
            },
        ),
        migrations.CreateModel(
            name='Shell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('instruction_text', models.CharField(blank=True, max_length=500, null=True)),
                ('instruction_image', models.ImageField(upload_to=shells.models.instruction_file_path)),
                ('resolution_text', models.CharField(blank=True, max_length=500, null=True)),
                ('resolution_image', models.ImageField(upload_to=shells.models.resolution_file_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shells.category')),
                ('difficulty_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shells.difficultylevel')),
            ],
            options={
                'verbose_name': 'Shell',
                'verbose_name_plural': 'Shells',
            },
        ),
        migrations.CreateModel(
            name='UserShell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_trained_date', models.DateField(blank=True, null=True)),
                ('time_spent_drill_instruction', models.FloatField(blank=True, null=True)),
                ('time_spent_drill_resolution', models.FloatField(blank=True, null=True)),
                ('trained_count', models.IntegerField(blank=True, null=True)),
                ('difficulty_evaluation', models.BooleanField(default=False)),
                ('has_liked', models.BooleanField(default=False)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True)),
                ('shell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shells.shell')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Shell',
                'verbose_name_plural': 'User Shells',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shell_count', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateField(auto_now=True)),
                ('candidate_shells', models.ManyToManyField(blank=True, related_name='candidate_shells', to='shells.shell')),
                ('categories', models.ManyToManyField(blank=True, to='shells.category')),
                ('completed_shells', models.ManyToManyField(blank=True, related_name='completed_shells', to='shells.shell')),
                ('dropped_shell', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropped_shell', to='shells.shell')),
                ('last_shell', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_shell', to='shells.shell')),
                ('session_shells', models.ManyToManyField(blank=True, related_name='session_shells', to='shells.shell')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training session',
                'verbose_name_plural': 'Training sessions',
            },
        ),
    ]
