# Generated by Django 4.2.2 on 2023-06-18 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shells', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='candidate_shells',
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
