# Generated by Django 4.2.2 on 2023-06-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shells', '0005_trainingsession_finished_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='finished_time',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='time_spent_session',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
