# Generated by Django 4.2.2 on 2023-06-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shells', '0006_remove_trainingsession_finished_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usershell',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usershell',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
