# Generated by Django 4.2.2 on 2023-06-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shells', '0007_alter_trainingsession_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershell',
            name='opened_resolution_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usershell',
            name='time_spent_drill_instruction',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usershell',
            name='time_spent_drill_resolution',
            field=models.FloatField(default=0),
        ),
    ]
