# Generated by Django 4.2.2 on 2023-07-26 22:14

from django.db import migrations, models
import shells.models


class Migration(migrations.Migration):

    dependencies = [
        ('shells', '0008_usershell_opened_resolution_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shell',
            name='knowledge_image',
            field=models.ImageField(blank=True, null=True, upload_to=shells.models.resolution_file_path),
        ),
        migrations.AddField(
            model_name='shell',
            name='knowledge_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
